### PR TITLE
FUSEDOC-3913: Minor editorial edits

### PR DESCRIPTION
**Pull request by nebelsprachen**
https://issues.redhat.com/browse/FUSEDOC-3913

Work in progress

### CODE REVIEW

**Comment by bfitzpat** [comment]
Thanks for the edits! Should we leave this PR open so you can make additional changes to it? Or do you want to break it up across multiple PRs?

**Comment by nebelsprachen** [comment]
@bfitzpat I have a few more edits to make, nothing major. Should have a completed PR by Monday, if that's ok :)

**Comment by bfitzpat** [comment]
@joaedwar Take your time! No rush on this. :)

**Review by Gerry-Forde — COMMENTED** [review]
@joaedwar @bfitzpat These changes look good to me...there is just one small typo _"important **prodcut** features"_

**Review by bfitzpat — COMMENTED** [review]
@joaedwar you have added some great questions in here. Can we add them to the agenda for Friday's meeting with Tiffany and the rest of the solution patterns working group?

**Pull request closed without merging**
